import CarouselSection from "@/components/CarouselSection";
import ContactUsForm from "@/components/contact-us/ContactUsSection";
import ContactMapSection from "@/components/contact-us/ContactMapSection";
import ContactInfosSection from "@/components/contact-us/ContactInfosSection";
import { Metadata } from "next";
import ReCaptchaProviderClient from "@/components/ReCaptchaProviderClient";

export const metadata: Metadata = {
  title: "Contact | DM COMPANY",
  description: "Generated by create next app",
};

export default function ContactPage() {
  return (
    <>
      <CarouselSection title="Contactez-nous" description="" />

      {/* Contact infos section */}
      <ContactInfosSection />

      {/* Formulaire */}
      <ReCaptchaProviderClient>
        <ContactUsForm />
      </ReCaptchaProviderClient>

      {/* Coordonnées et carte */}
      <ContactMapSection />
    </>
  );
}
