import CarouselSection from "@/components/CarouselSection";
import ContactMapSection from "@/components/MapSection";
import ContactInfosSection from "@/components/contact-us/ContactInfosSection";
import { Metadata } from "next";
import ContactUsClient from "@/components/contact-us/ContactUsClient";

export const metadata: Metadata = {
  title: "Contact | DM COMPANY",
  description: "Generated by create next app",
};

export default function ContactPage() {
  return (
    <>
      <CarouselSection title="Contactez-nous" description="" />

      {/* Contact infos section */}
      <ContactInfosSection />

      {/* Formulaire */}
      <ContactUsClient />

      {/* Coordonnées et carte */}
      <ContactMapSection />
    </>
  );
}
