import CarouselSection from "@/components/CarouselSection";
import React from "react";
import activities from "@/mock/activities.json";
import ActivityCard from "@/components/our-activities/ActivityCard";
import InfoSection from "@/components/our-activities/InfoSection";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Nos activités | DM COMPANY",
  description: "Generated by create next app",
};

export default function OurActivitiesPage() {
  return (
    <>
      <CarouselSection title="Nos activités" description="" />
      <InfoSection />
      <div className="max-w-7xl mx-auto px-4 py-16 grid gap-8 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
        {activities.map((act) => (
          <ActivityCard key={act.id} activity={act} />
        ))}
      </div>
    </>
  );
}
