import AboutSection from "@/components/AboutSection";
import DomainsSection from "@/components/DomainsSection";
import PartnersSection from "@/components/PartnersSection";
import HomeCarouselSection from "@/components/HomeCarouselSection";
import { Metadata } from "next";
import ContactMapSection from "@/components/contact-us/ContactMapSection";

export const metadata: Metadata = {
  title: "Accueil | DM COMPANY",
  description: "Generated by create next app",
};

const HomePage = () => {
  return (
    <div className="">
      {/* CAROUSEL */}
      <HomeCarouselSection />

      {/* QUI SOMMES NOUS */}
      <AboutSection />

      {/* DOMAINES D’ACTIVITÉ */}
      <DomainsSection />

      {/* PARTENAIRES */}
      <PartnersSection />

      {/* ACTIVITÉS RÉCENTES */}
      {/* <RecentSection /> */}

      {/* MAP */}
      <ContactMapSection />
    </div>
  );
};

export default HomePage;
